### ISSUE TITLE
ESP32 Arduino: Payloads report zeros after some time

### ISSUE THREAD

**Issue by paulhart** [theengs/decoder#247]
**Describe the bug**
I'm using the attached code to log data from several BLE temperature sensors and save the data via a web API:

[code_sample.txt](https://github.com/theengs/decoder/files/10308394/code_sample.txt)

After some time (hours), the payload data is all reported as zeros. The code is intended to find these scenarios and reset the ESP32, but it'd be nice if I didn't have to (try to) bounce it!

**To Reproduce**
1. Run data collection for several hours

**Expected behavior**
Expected to continue to see valid payload data from the temperature sensors

**Environment (please complete the following information):**
* Arduino 1.8.19
* ArduinoJson 6.19.4
* NimBLE-Arduino 1.4.1
* TheengsDecoder 0.9.7

**Comment by h2zero** [comment]
I suspect this has more to do with the BLE stack than the decoder repo. Can you post a log with NimBLE debug logs enabled?

**Comment by paulhart** [comment]
I'll have a go... will see what I can do about having the ESP32 board connected to a computer for an extended period.

**Comment by paulhart** [comment]
Of course I haven't been able to replicate yet... however, I wonder if my issue is related to the following:

https://github.com/h2zero/NimBLE-Arduino/issues/460 which then links to
https://github.com/espressif/esp-idf/issues/9384

(I don't think I'm getting a restart, but the logs may say otherwise...)

**Comment by h2zero** [comment]
That's what I am suspecting.

**Comment by DigiH** [comment]
@paulhart any update on this? Can this Decoder specific issue be closed?

**Comment by DigiH** [comment]
Closing, as this looks very much like

https://github.com/h2zero/NimBLE-Arduino/issues/460

and not Decoder related.
