### ISSUE TITLE
BTHome decoder

### ISSUE THREAD

**Issue by AlexisBRENON** [theengs/decoder#249]
There seems to have a lot of different protocol/format used to send information other bluetooth. 
An attempt to provide a "standard" format is made by [BTHome](https://bthome.io/).
May a decoder be implemented for BTHome frames, or do I not understand anything of the IoT world ?

**Comment by koenvervloesem** [comment]
BTHome is a very interesting standard. However, its advertisements can have multiple measurements with varying length in one payload. Currently Theengs Decoder isn't able to specify how to decode variable payloads with the flexibility that BTHome has. So we would need some changes in Theengs Decoder before a BTHome decoder can be implemented.

**Comment by DigiH** [comment]
You're correct, there are a lot of different protocols/formats used for encoding relevant information in BLE braodcast data. 

This makes is interesting, sometimes annoying and frustrating, to reverse engineer these protocols to be able to decode them - something Decoder and other BLE decoders do to the best of their ability.

The BTHome format will also be included in a future Theengs Decoder update, but as you might have seen on the BTHome site, this format will likely only ever be included by other open source projects but not by companies with commercial products. These will undoubtedly stick to their proprietary formats and protocols, which will keep requiring individual specialised decoders for each of these protocols.

**Comment by AlexisBRENON** [comment]
Thanks for your feedbacks. I close the issue as it is not doable for the moment.
