### ISSUE TITLE
installation problem (ArduinoJson.h: No such file or directory)

### ISSUE THREAD

**Issue by jeremyarnoux** [theengs/decoder#270]
Hi,
I have a problem installing the decoder.
Can you help me please ?

Scanning dependencies of target decoder
[ 16%] Building CXX object CMakeFiles/decoder.dir/src/decoder.cpp.o
In file included from /home/pi/bluetooth/decoder-development/src/decoder.cpp:22:
/home/pi/bluetooth/decoder-development/src/decoder.h:26:10: fatal error: ArduinoJson.h: No such file or directory
 #include "ArduinoJson.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/decoder.dir/build.make:63: CMakeFiles/decoder.dir/src/decoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:617: CMakeFiles/decoder.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
pi@jeedom:~/bluetooth/decoder-development/python$ make
[ 16%] Building CXX object CMakeFiles/decoder.dir/src/decoder.cpp.o
In file included from /home/pi/bluetooth/decoder-development/src/decoder.cpp:22:
/home/pi/bluetooth/decoder-development/src/decoder.h:26:10: fatal error: ArduinoJson.h: No such file or directory
 #include "ArduinoJson.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/decoder.dir/build.make:63: CMakeFiles/decoder.dir/src/decoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:617: CMakeFiles/decoder.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by koenvervloesem** [comment]
```
git submodule update --init --recursive
```

**Comment by jeremyarnoux** [comment]
sorry I did not understand. what should i do with your command line?
command line not working
I have to install arduinojson?

**Comment by koenvervloesem** [comment]
Sorry for the short reply, I was busy then.

I suppose you cloned the repository with:

```
git clone https://github.com/theengs/decoder.git
```

Then when you enter the directory, you first need to update the submodule for ArduinoJson:

```
git submodule update --init --recursive
```

After this, you can continue with configuring and building Theengs Decoder as you did with `cmake`.

If my assumption is incorrect, please show the exact commands you entered when "installing the decoder", so we can see what it is you're trying to do.

**Comment by jeremyarnoux** [comment]
everything is ok, thank you very much !!!
