### ISSUE TITLE
scan Aborted

### ISSUE THREAD

**Issue by jeremyarnoux** [theengs/decoder#273]
Hi,
I'm working on a plugin for Jeedom in partnership with Switchbot who generously sent me all of their hardware for testing.
So I would like to complete the list of devices :-)

Je rencontre un petit problème lorsque je lance le scan, j'ai l'erreur suivante : 
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted

Do you have any idea where the problem comes from?
Thanks for your help !!!

`pi@jeedom:~/bluetooth/decoder/examples/python$ python3 ScanAndDecode.py
CD:2D:2A:D7:FD:AA RSSI: -78 AdvertisementData(manufacturer_data={2409: b'\xcd-*\xd7\xfd\xaa\x92,\x10\x9f'}, rssi=-78)
data sent to decoder:  {"manufacturerdata": "6909cd2d2ad7fdaa922c109f"}
TheengsDecoder found device: None
00:00:00:00:00:00 RSSI: -78 AdvertisementData(rssi=-78)
56:41:61:68:61:6D RSSI: -31 AdvertisementData(rssi=-31)
C6:8A:0E:B8:51:72 RSSI: -74 AdvertisementData(manufacturer_data={89: b'\xc6\x8a\x0e\xb8Qr'}, service_data={'00000d00-0000-1000-8000-00805f9b34fb': b'c@@c\x11\x04'}, service_uuids=['cba20d00-224d-11e6-9fb8-0002a5d5c51b'], rssi=-74)
data sent to decoder:  {"servicedatauuid": "0d00", "servicedata": "634040631104", "manufacturerdata": "5900c68a0eb85172"}
TheengsDecoder found device: None
02:0D:00:00:00:00 RSSI: 89 AdvertisementData(rssi=89)
DF:3A:05:45:33:F6 RSSI: -64 AdvertisementData(manufacturer_data={2409: b'\xdf:\x05E3\xf6\x00\xffc\xd9[S'}, rssi=-64)
data sent to decoder:  {"manufacturerdata": "6909df3a054533f600ff63d95b53"}
TheengsDecoder found device: None
A8:03:2A:C3:91:3A RSSI: -74 AdvertisementData(manufacturer_data={741: b'\xa8\x03*\xc3\x91:'}, rssi=-74)
data sent to decoder:  {"manufacturerdata": "e502a8032ac3913a"}
TheengsDecoder found device: None
84:F7:03:AF:EC:06 RSSI: -66 AdvertisementData(manufacturer_data={2409: b'\x84\xf7\x03\xaf\xec\x06\x8d\\"\x00\x00'}, rssi=-66)
data sent to decoder:  {"manufacturerdata": "690984f703afec068d5c220000"}
TheengsDecoder found device: None
FB:65:48:0A:ED:16 RSSI: -62 AdvertisementData(manufacturer_data={2409: b'\xfbeH\n\xed\x16\t\x83\x08 '}, rssi=-62)
data sent to decoder:  {"manufacturerdata": "6909fb65480aed1609830820"}
TheengsDecoder found device: None
DF:3A:05:45:33:F6 RSSI: -64 AdvertisementData(manufacturer_data={2409: b'\xdf:\x05E3\xf6\x00\xffc\xd9[S'}, rssi=-68)
data sent to decoder:  {"manufacturerdata": "6909df3a054533f600ff63d95b53"}
TheengsDecoder found device: None
CB:AC:B0:D9:7B:5C RSSI: -84 AdvertisementData(manufacturer_data={2409: b'\xcb\xac\xb0\xd9{\\\xe6n3X\xff\xffB'}, rssi=-84)
data sent to decoder:  {"manufacturerdata": "6909cbacb0d97b5ce66e3358ffff42"}
TheengsDecoder found device: None
C5:2B:C2:A1:CF:8B RSSI: -78 AdvertisementData(manufacturer_data={89: b'\xc5+\xc2\xa1\xcf\x8b'}, rssi=-78)
data sent to decoder:  {"manufacturerdata": "5900c52bc2a1cf8b"}
TheengsDecoder found device: None
A0:76:4E:36:4A:C6 RSSI: -70 AdvertisementData(manufacturer_data={2409: b'\xa0vN6J\xc6\x8a\xbc"\x0c\x00\x00\x00\x00\x00\x00'}, service_data={'0000fd3d-0000-1000-8000-00805f9b34fb': b'r\x00d'}, rssi=-70)
data sent to decoder:  {"servicedatauuid": "fd3d", "servicedata": "720064", "manufacturerdata": "6909a0764e364ac68abc220c000000000000"}
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
pi@jeedom:~/bluetooth/decoder/examples/python$
`

**Comment by DigiH** [comment]
The last device is a SwitchBot LED Strip Light, correct?

Which is not supported by Decoder (yet), so no decoding expected, but it also shouldn't throw an exception and terminate the scan.

Investigating about the exception …

@jeremyarnoux, could you try this branch in which i have included a change which should fix your issue for the time being

https://github.com/DigiH/decoder/tree/TPMS-test

**Comment by DigiH** [comment]
@jeremyarnoux  - has your issue been fixed with the above change in the latest dev branch?

**Comment by alrzbv** [comment]
Hello,
I'm got this error when using [ScanAndDecode.py](https://github.com/theengs/decoder/blob/development/examples/python/ScanAndDecode.py) (use actual code from develompent branch):

D4:58:B1:7D:98:39 RSSI: -75 AdvertisementData(local_name='Amazfit Bip Watch', manufacturer_data={343: b'\x00\xde \xf8\xb6V4\x06\xaf\x81u\xab\x1c\xd2\x8a\x01\x19\x03\xd4X\xb1}\x989'}, rssi=-75)
data sent to decoder:  {"manufacturerdata": "570100de20f8b6563406af8175ab1cd28a011903d458b17d9839", "name": "Amazfit Bip Watch"}
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    2796 abort      python ScanAndDecode.py

**Comment by DigiH** [comment]
Thanks for the report. I'll have to have a closer look at this.

@alrzbv @jeremyarnoux the Python example you both have likely been using is missing sending the MAC address to Decoder, which is necessary for some decoders to work.

We'll need to amend the example, please hold on for a bit …

**Comment by DigiH** [comment]
@alrzbv @jeremyarnoux, can you amend your code with the additions in

https://github.com/theengs/decoder/commit/b53ab08536145f44f1244d2c11f3f7e1cefe6313

and give feedback if this issues is resolved with it?

**Comment by alrzbv** [comment]
no more errors, for me. thx!

**Comment by DigiH** [comment]
Closing, as the example additions have been integrated into the 1.2.0 release.
