### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by blacklight** [theengs/decoder#292]
**Is your feature request related to a problem? Please describe.**

I need to use the decoder library in another project that already uses bleak to handle the Bluetooth connections - basically, I need a reliable parser of advertisement packets that can be installed via pip.

**Describe the solution you'd like**

Release pre-compiled packages of the decoder library that can be installed via pip.

**Describe alternatives you've considered**

- Importing the whole Theengs gateway as a dependency for my project, since that already comes with a pre-compiled version of the library
- Building the decoder library manually

**Comment by 1technophile** [comment]
@BlackLight could you test this please:
```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple TheengsDecoder==1.2.0b3
```

**Comment by blacklight** [comment]
Thanks @1technophile, that works!

**Comment by DigiH** [comment]
Closing, as from release 1.3.0 TheengsDecoder is at

https://pypi.org/project/TheengsDecoder/
