### ISSUE TITLE
New WS08 ThermoBeacon devices not supported anymore

### ISSUE THREAD

**Issue by eazores** [theengs/decoder#296]
**Describe the bug**
Hi!

I just bought 2 WS08 ThermoBeacon devices (FCC id 2ACD3-WS08).
The parsing of the advertising manufacturer data does not perform as expected.

It seems like for new devices the advertising manufacturer data has changed as of dec 22, see the issue fixed in Home Assistant:
[Fix thermobeacon WS08 models that identify with manufacturer_id 27](https://github.com/home-assistant/core/issues/84706)

So this could be the issue for my devices too, or something else.

**To Reproduce**
I'm not using a development environment, just [OpenMQTTGateway v1.4.0](https://docs.openmqttgateway.com/) (which seems like the theengs decoder v1.2.0) on an esp32 board [esp32dev-ble-openhab](https://docs.openmqttgateway.com/prerequisites/boards/esp32dev-ble-openhab)

**Expected behavior**
My device advertises its manufacturer data as:
{length = 20, bytes = 0x1 b002500cf1d0000d063a50cdcOObf0338270000}

I expected the output to be something in the vein of a nice json containing the brand, model, tempc, hum, volt values...

but I just get

"manufacturerdata":"1b002500cf1d0000d063a40cdc00bf0332270000"

**Screenshots**
![IMG_2716](https://user-images.githubusercontent.com/127129665/223172198-46ebfc51-9d6d-4420-b92c-2a8fdc323402.PNG)
![IMG_2715](https://user-images.githubusercontent.com/127129665/223172209-456794b5-b801-46ba-a82e-ef550157d36c.PNG)

**Environment (please complete the following information):**
OpenMQTTGateway v1.4.0
esp32dev-ble-openhab on esp32 board
WS08 ThermoBeacon devices (FCC id 2ACD3-WS08)

**Comment by DigiH** [comment]
Hi @eazores,

thanks for letting us know and stating your new undecoded  manufacturerdata.

Would these be correct for your above manufacturerdata example?

`{"brand":"GENERIC","model":"ThermoBeacon","model_id":"WS02/WS08","type":"THB","cidc":false,"tempc":13.75,"tempf":56.75,"hum":59.9375,"volt":3.236,"time":10034}
`

I'm implementing a fix now and will have a test version ready for you to try in about an hour.

**Comment by eazores** [comment]
Thanks @DigiH these temp, hum, volt, and time values seem correct 👍

But just to make sure, could you parse the following data so that I could double check with the values provided with the "Sensor Blue" app ?

(length = 20, bytes = 0x1b002500cf1d0000d063850cdb00d903c7390000}

**Comment by DigiH** [comment]
The above was parsed with your

`"manufacturerdata":"1b002500cf1d0000d063a40cdc00bf0332270000"`

the test build is running, so in about an hour you can web upload a test version of your previously used `esp32dev-ble-openhab`

**Comment by DigiH** [comment]
@eazores 
The test build can be uploaded from

https://docs.openmqttgateway.com/dev/upload/web-install.html

Please let me know if it is working fine for you.

**Comment by eazores** [comment]
Thanks for the build @DigiH, I gave it a go and the parsing is spot on 👍 and I don't have any issues anymore.

**Comment by hildigrim** [comment]
Hi

I can add another manufacturer id to the mix. 
My 6-9 months old SenorBlue WS08s have an id of 15.

Example:
1500000010070000bb8e140b6c01dd02f0d47200
1500000010070000bb8eb401faa530002601c66f6700

**Comment by DigiH** [comment]
Thanks for the additional ID @hildigrim 

This has been included in the decoder and can be verified with the above linked test dev build tomorrow after the nightly builds, or with you updating your fork.

**Comment by DigiH** [comment]
Closing, as all currently known IDs have been included in the WS08 decoder now.
