### ISSUE TITLE
BM2 battery monitor showing 100% battery only

### ISSUE THREAD

**Issue by dopacak** [theengs/decoder#368]
**Describe the bug**
Theengs detected BM2 battery monitor, but only shows a single sensor which display only 100%, not actual values like voltage. 

**To Reproduce**
1. Data processed
2. Expected voltage reading from device in mqtt
3. Showing 100%, not voltage 

**Environment (please complete the following information):**
* version used (theengs gateway for HA v1.8)

**Additional context**
Read technophiles post on HA forum mentioning it should work under theengs and OMG. Unsure if this part of the component is using the correct theengs decoder, or if I'm doing something wrong 

Thanks!

**Comment by 1technophile** [comment]
Hmm, which post are you referring to?
Voltage reading is only implemented with OMG for the moment. Theengs reads battery only

**Comment by dopacak** [comment]
I read it was it was integrated with theengs and OMG, assumed both would get voltage. My mistake. Will theengs obtain this data or should I just put omg onto a esp32? Thanks!

**Comment by 1technophile** [comment]
Not planning to add it to Theengs short term, so if you need it now you better go with an esp32. Also note that as most of the time battery are inside a metallic structure, so it is easier to get the signal by pluging an esp32 nearby.

**Comment by dopacak** [comment]
Thanks Florian. Appreciate the assistance

**Comment by DigiH** [comment]
Closing as currently N/A for Decoder
