### ISSUE TITLE
No mqtt data on iOS

### ISSUE THREAD

**Issue by london89** [theengs/decoder#388]
When I added LYWSD03MMC to iOS app, I can see temperature and humidity, can update it.
But in MQTT no data about this.
In MQTT i see only topic home/TheengsApp/version with data "v1.3.1"

1. Install app
2. add LYWSD03MMC 
3. configure mqtt server settings
4. scan MAC of LYWSD03MMC with debian
5. Set MAC Address of my LYWSD03MMC into App, from previous scan
"root@mdm:/home/london# stdbuf -oL hcitool lescan | grep LYWSD03MMC
A4:C1:38:5C:75:B6 LYWSD03MMC"
6. click Update data in app

**Expected behavior**
I wanna LYWSD03MMC data in MQTT

![photo_2023-07-04_20-38-02 (2)](https://github.com/theengs/decoder/assets/28978333/1052c195-8f2b-4e22-9950-fc2a13dab1cf)
![photo_2023-07-04_20-38-02](https://github.com/theengs/decoder/assets/28978333/8e0c250c-67f7-4afd-bf2c-5513c44fd2b7)
![photo_2023-07-04_20-38-00](https://github.com/theengs/decoder/assets/28978333/b7e0db6b-8fdb-44d8-9313-52c739127806)
![photo_2023-07-04_20-37-59](https://github.com/theengs/decoder/assets/28978333/1d13c1fe-62ce-4547-87d1-fd1dfe1aa657)

iOS App Theengs ver 1.3.1
iPhone 14 Pro
iOS ver. 16.5.1

**Comment by london89** [comment]
not to decoder

**Comment by DigiH** [comment]
Hi @london89 

No worries, more of a Theengs App issue, but we can handle it here.

Can you make sure you add your LYWSD03MMC's MAC address at the top right three dots menu - **Set MAC address**.

As iOS does not allow to recognise devices' MAC addresses, but masks them with random uuids, this is required to be able to assign a constant MAC address to each device. Only then can it publish with this MAC address/id to an MQTT broker.

**Comment by london89** [comment]
> Can you make sure you add your LYWSD03MMC's MAC address at the top right three dots menu - **Set MAC address**.

of course, you can see it on my screenshot

**Comment by london89** [comment]
lets close this issue, it was my mistake. lets resume here https://github.com/theengs/app/issues/91
