### ISSUE TITLE
Allow iBeacon decoder to correctly report the battery level for iBeacons which transmit this throws an exception

### ISSUE THREAD

**Issue by DigiH** [theengs/decoder#39]
Allow iBeacon decoder to correctly report the battery level for iBeacons which transmit this instead of the tc power at "manufacturerdata", 48, 2

Since I have iBeacons which transmit the tx power as well as iBeacons which at the same index of the manufacturerdata transmit the battery level I have so far made the distinction and reporting in openHAB. With the new theengs decoders the tx power is reported fine for such iBeacons, but the battery power transmitting ones are falsely reporting an ever changing tx power.

Having tested a bit with the decoder definition the following

```
const char* _ibeacon_json = "{\"brand\":\"GENERIC\",\"model\":\"IBEACON\",\"model_id\":\"IBEACON\",\"condition\":[\"manufacturerdata\",\"=\",50,\"index\",0,\"4c00\"],\"properties\":{\"mfid\":{\"decoder\":[\"string_from_hex_data\",\"manufacturerdata\",0,4]},\"uuid\":{\"decoder\":[\"string_from_hex_data\",\"manufacturerdata\",8,32]},\"major\":{\"decoder\":[\"value_from_hex_data\",\"manufacturerdata\",40,4,false]},\"minor\":{\"decoder\":[\"value_from_hex_data\",\"manufacturerdata\",44,4,false]},\"battery\":{\"decoder\":[\"value_from_hex_data\",\"manufacturerdata\",48,2,false],\"post_proc\":[\"/\",10]}}}";
/*R""""(
{
   "brand":"GENERIC",
   "model":"IBEACON",
   "model_id":"IBEACON",
   "condition":["manufacturerdata", "=", 50, "index", 0, "4c00"],
   "properties":{
      "mfid":{
         "decoder":["string_from_hex_data", "manufacturerdata", 0, 4]
      },
      "uuid":{
         "decoder":["string_from_hex_data", "manufacturerdata", 8, 32]
      },
      "major":{
         "decoder":["value_from_hex_data", "manufacturerdata", 40, 4, false]
      },
      "minor":{
         "decoder":["value_from_hex_data", "manufacturerdata", 44, 4, false]
      },
      "battery":{
         "decoder":["value_from_hex_data", "manufacturerdata", 48, 2, false],
         "post_proc":["/", 10]
      }
   }
})"""";*/

const char* _ibeacon_json_props = "{\"properties\":{\"mfid\":{\"unit\":\"hex\",\"name\":\"manufacturer id\"},\"uuid\":{\"unit\":\"hex\",\"name\":\"service uuid\"},\"major\":{\"unit\":\"hex\",\"name\":\"major value\"},\"minor\":{\"unit\":\"hex\",\"name\":\"minor value\"},\"battery\":{\"unit\":\"Volt\",\"name\":\"battery\"}}}";
/*R""""(
{
   "properties":{
      "mfid":{
         "unit":"hex",
         "name":"manufacturer id"
      },
      "uuid":{
         "unit":"hex",
         "name":"service uuid"
      },
      "major":{
         "unit":"hex",
         "name":"major value"
      },
      "minor":{
         "unit":"hex",
         "name":"minor value"
      },
      "battery":{
         "unit":"Volt",
         "name":"battery"
      }
   }
})"""";*/
```

works fine in reporting

`…,"major":1,"minor":1,"battery":1.5}`
and
`…,"major":1,"minor":2,"battery":2.8}`

for two of my battery voltage transmitting iBeacons. 

So my idea was to have both the tx power and battery voltage included in the decoder, both with appropriate conditions, as in

```
…
"power":{
         "condition":["manufacturerdata", 48, "b"],
         "decoder":["value_from_hex_data", "manufacturerdata", 48, 2, false]
      },
      "battery":{
         "condition":["manufacturerdata", 48, "0"],
         "decoder":["value_from_hex_data", "manufacturerdata", 48, 2, false],
         "post_proc":["/", 10]
      }
…
```

obviously along with the appropriate _ibeacon_json and _ibeacon_json_props definitions.

Trying this I came across two issues:
• even just adding the condition **"condition":["manufacturerdata", 48, "0"],** to the plain vanilla battery only iBeacon_json.h above, which should report my 1.5 V iBeacon, OMG throws an exception, whenever an iBeacon is recognised. While the docs say, that "manufacturerdata" is a valid properties condition, I have not found any other decoders, which have a manufacturerdata properties condition. Could there be an issue with it - or where is my thinking wrong here?

• Also, if the manufacturerdata properties condition would not throw an exception, to fully implement the tx power vs. battery voltage differentiation it would require many OR conditions, with "condition":["manufacturerdata", 48, "8"] up to "condition":["manufacturerdata", 48, "f"] to recognise as tx power **and** "condition":["manufacturerdata", 48, "0"] up to "condition":["manufacturerdata", 48, "7"] for the battery voltage. Any possibility to have such ranges definitions shortened in properties conditions?

Any help with why my currently testing properties condition with manufacturerdata throwing an exception would be greatly appreciated, as without the manufacturerdata properties conditions it is either tx power or battery voltage.

A possibly shorter range definition might be a nice to have for the future.

**Comment by h2zero** [comment]
Hi @DigiH there does seem to be a bug in the case of "manufacturerdata" as a conditions for the property. As you noted none of the other devices use this so it has gone undetected. I will PR a fix for this shortly and I would appreciate your testing of it when possible.
