### ISSUE TITLE
Report HHCCJCY01HHCC battery 

### ISSUE THREAD

**Issue by marcokreeft87** [theengs/decoder#406]
**Is your feature request related to a problem? Please describe.**
Why isn't the battery status of  HHCCJCY01HHCC  reported? Its reporting the status in the app.
According to the source [HHCCJCY10](https://github.com/theengs/decoder/blob/development/src/devices/HHCCJCY10_json.h) does report the battery status. MAC isnt reported btw.

**Describe the solution you'd like**
Update [this file](https://github.com/theengs/decoder/blob/development/src/devices/HHCCJCY01HHCC_json.h) to report the battery status of the device. 

**Describe alternatives you've considered**
I've considered pulling the source and trying it myself but it would probably be quicker for the code owners to do it.

**Additional context**
![image](https://github.com/theengs/decoder/assets/10223677/92b38fc1-9e9c-4868-8df9-e9e6cfbc3c7f)
In the screenshot you can see mac isnt working

**Comment by DigiH** [comment]
Hi @marcokreeft87 

You are correct, the battery status of a  HHCCJCY01HHCC is not being reported by Theengs Gateway, which uses Decoder to only receive and decode the freely broadcast advertisement data - the sole present functionality of Theengs Decoder.

The HHCCJCY01HHCC advertising servicedata does not include the battery information. 

OpenMQTTGateway, on the other hand, does also report the battery status of HHCCJCY01HHCCs, but by doing this separately through an active connection to the HHCCJCY01HHCC devices.

The MAC address however should be received and decoded, if release 1.5.5 or later of Theengs Decoder is being used in the project. I think that might be the issue you are currently seeing with the latest Theengs Gateway release still using Decoder 1.5.0. The MAC address will show correctly with the next Gateway update.

We are currently looking at possibilities on how to best include this connection property feature across all projects, but currently these are only available with OpenMQTTGateway.

Hope this clarifies the issues you are seeing.

**Comment by DigiH** [comment]
Closing as N/A to Theengs Decoder.

**Comment by marcokreeft87** [comment]
Yes it's clear, thnx! I will wait till you guys figure it out
