### ISSUE TITLE
Add support for PAX Calima

### ISSUE THREAD

**Issue by wioxjk** [theengs/decoder#481]
**Support for PAX Calima**

I have a couple of PAX Calima fan in my house, unfortunately - the are out of range from my Home Assistant machine and I am unable to relocate it closer.

I have thought about getting an ESP32 and create a bluetoothproxy on it, but since I already have a Raspberry Pi Zero W, it would be nice to utilize this.

Here is the drivers for those fans:

https://github.com/PatrickE94/pycalima

The drivers is successfully used in this project that works great with Home Assistant:
https://github.com/eriknn/ha-pax_ble

Thank you for your work!

**Comment by DigiH** [comment]
From briefly looking at your provided links, it seems that reading the properties for PAX Calima requires a connection to the devices to read the appropriate service/char, and obviously writing any commands also requires connections.

Theengs Decoder is designed to only receive freely broadcast advertising data from devices, so there doesn't seem to be any possibility for that with PAX Calima.

Looks like your best bet in an ESP32 as a procy for the above HA integration.

Closing as not applicable.

If you think there is usable and decodable advertising data sent out by these devices, feel free to re-open the issue.

**Comment by wioxjk** [comment]
Thank you for taking the time to respond!
An ESP32 it is then.
