### ISSUE TITLE
ScanAndDecode.ino connect or not connect ?

### ISSUE THREAD

**Issue by ioukos** [theengs/decoder#520]
Hello,

Is this ScanAndDecode.ino sketch operating in connected or disconnected mode ? I understand it's in scan mode so not connected. It's better I think because it's less power consuming on the Xiaomi side.

I also would like to knwo if this skectch is compliant with : https://github.com/pvvx/ATC_MiThermometer .

Thank you.

**Comment by DigiH** [comment]
Hello @ioukos 

Correct, it only scans for BLE advertising broadcasts, either passive or active, depending on the project. There is no connection functionality in Theengs Decoder, but again could be supported by a project, as OpenMQTTGateway allows for READ and WRITE connections.

> I also would like to knwo if this skectch is compliant with : https://github.com/pvvx/ATC_MiThermometer .

This is the list of all currently supported devices of Theengs Decoder

https://decoder.theengs.io/devices/devices.html

which includes several of the PVVX firmware compatible devices.

Hope this helps.
