### ISSUE TITLE
Mi band 7 no steps

### ISSUE THREAD

**Issue by murfy76** [theengs/decoder#522]
Hello, I'm unable to get steps from Mi band 7 (firmware 2.1.0.1) only heart rate. I'm using latest stable and development version of OpenMqttGateway. I've tried to downgrade Zepp Life to previous v6.9.6 version but no difference. In recent and this version of Zepp Life there is only option for "Activity heart rate sharing" no steps. What I'm missing? Thank you.  

Peter

{"id":"D3:EB:1F:22:65:11","name":"Xiaomi Smart Band 7 6511","rssi":-72,"distance":4.287841,"brand":"Xiaomi/Amazfit","model":"Mi Band/Smart Watch","model_id":"MB/SW","type":"BODY","act_bpm":0,"device":"Xiaomi/Amazfit Tracker","mac":"D3:EB:1F:22:65:11"}

**Comment by DigiH** [comment]
Hi @murfy76 

This is a known issue as unfortunately seems apparent that the steps are no longer broadcast freely with the advertising data with the Mi Band 7, which was fine with Mi Bands up to version 6.

https://github.com/theengs/decoder/issues/422

https://github.com/1technophile/OpenMQTTGateway/issues/1642
