### ISSUE TITLE
Is Theengs supported running in Windows?

### ISSUE THREAD

**Issue by simowilso** [theengs/decoder#537]
**Describe the bug**
Installing Theengs in Windows results in numerous errors
Not sure if it's supported?

**To Reproduce**

pip install TheengsGateway

**Expected behavior**

**Screenshots**

https://pastebin.com/2T4YwMwp

**Environment**
**Additional context**
Add any other relevant context about the problem here.

**Comment by koenvervloesem** [comment]
Installing Theengs Gateway builds Theengs Decoder, which fails according to your pastebin output because it can't find the necessary build tools: "Building windows wheels for Python 3.12 requires Microsoft Visual Studio 2022."

We don't support Windows officially, but in principle it should work if you manage to build it.

**Comment by 1technophile** [comment]
I have it working on Windows 11 but I have Microsoft Visual Studio installed

**Comment by simowilso** [comment]
I've installed VS2022 but same error. Not sure if i have to install some extra package(s) in VS?

Perhaps running Theengs on a Mac is simpler? I don't have a Linux laptop available right now and it won't run on WSL (I've raised a separate issue for that)

**Comment by DigiH** [comment]
> Perhaps running Theengs on a Mac is simpler? I don't have a Linux laptop available right now and it won't run on WSL (I've raised a separate issue for that)

While running fine, unfortunately on macOS there are no proper MAC addresses being published, but random UUIDs, a macOS wide Bluetooth _feature_ to obfuscate disctinct MAC addresses. Will be good enough for some sample messages from your Victron gear, but not really as a constant gateway for inclusion in a controller set-up.

> I've installed VS2022 but same error. Not sure if i have to install some extra package(s) in VS?

Possibly a CMake extension? And is your Python version 3 on Windows?
