### ISSUE TITLE
Decoder for BFOUR Bf-40 / Grill BT5.0 BBQ Thermometer

### ISSUE THREAD

**Issue by hs75** [theengs/decoder#550]
**Is your feature request related to a problem? Please describe.**
BBQ thermometer is used to measure food temperature during cooking. it would be helpful to have temperature also avaiolable in MQTT, e.g. to switch off heating when food is ready

**Describe the solution you'd like**
Decoder, thath helps gateway to extract temperature from BLE traffic and post it via MQTT

**Describe alternatives you've considered**
None

**Additional context**
sanitized log of BLE messages
xx:xx:xx.xxxx: connected in underlying BLE layer.
xx:xx:xx.xxxx: discovered services: (
    FE59,
    FFB0
)
xx:xx:xx.xxxx: discovered characteristics for service FFB0: (
    FFB1,
    FFB2
)
xx:xx:xx.xxxx: discovered characteristics for service FE59: (
    “xxxxxxxx—xxxx-xxxx-xxxxxxxxxxxxxxxxx“,
    “xxxxxxxx—xxxx-xxxx-xxxxxxxxxxxxxxxxx“,
    0003
)
xx:xx:xx.xxxx: state changed to 'Connected'.
xx:xx:xx.xxxx: updated subscription state for characteristic FFB2___FFB0: subscribed
xx:xx:xx.xxxx: updated subscription state for characteristic FFB2___FFB0: subscribed
xx:xx:xx.xxxx: received update from characteristic FFB2___FFB0: <55000163 ffffffff ffffffff ffffff>
xx:xx:xx.xxxx: received update from characteristic FFB2___FFB0: <55000163 ffffffff ffffffff ffffff>
xx:xx:xx.xxxx: received update from characteristic FFB2___FFB0: <55000163 ffffffff ffffffff ffffff>
xx:xx:xx.xxxx: received update from characteristic FFB2___FFB0: <55000164 ffffffff ffffffff ffffff>

**Comment by DigiH** [comment]
Hi @hs75 

Does the BFOUR Bf-40 also send it's temperatures through its freely broadcast BLEW advertising data? As this is currently the only way Theengs Decoder can get encoded data from, but not from connections.

If you could set [Advertisement and Advanced Data](https://docs.openmqttgateway.com/use/ble.html#advanced-advertisement-and-advanced-data-default-false-available-with-ha-discovery) to **true** and monitoring the broadcasts through MQTT Explorer, to see if there is any decodable data in the broadcasts.
