### ISSUE TITLE
Add support for Shelly BLU H&T

### ISSUE THREAD

**Issue by GeoChallenger** [theengs/decoder#551]
Details of the device: [https://shelly-api-docs.shelly.cloud/docs-ble/Devices/ht](url)

Example of current output data
{
  "manufacturerdata": "a90b0111000b03000ab54cbdb6c67c",
  "name": "SBHT-003C",
  "id": "7C:C6:B6:xx:yy:zz",
  "rssi": -55,
  "servicedatauuid": "fcd2",
  "servicedata": "44004e01642e3f45df00",
  "mfr": "Allterco Robotics ltd"
}

**Comment by DigiH** [comment]
I'm currently away and won't be able to look at this for a while.

**Comment by GeoChallenger** [comment]
> I'm currently away and won't be able to look at this for a while.

When can some change in this case be done?

**Comment by DigiH** [comment]
I assume this is the same Shelly Temperature and Humidity sensor for which chrestme is working on creating a decoder for Theengs Decoder [here](https://github.com/theengs/decoder/discussions/553)

**Comment by GeoChallenger** [comment]
> I assume this is the same Shelly Temperature and Humidity sensor for which chrestme is working on creating a decoder for Theengs Decoder [here](https://github.com/theengs/decoder/discussions/553)

Indeed, this is what I'm waiting for.

**Comment by DigiH** [comment]
You could help along by posting more output data as in your initial post and stating the **temperature**, **humidity** and **battery level** as shown in the Shelly app at the very same time, so that we can reverse engineer the encoded data for a decoder.

**Comment by DigiH** [comment]
Closing, as the ShellyBLU H&T SBHT-003C decoders have been merged into development, and will be in the next release, also currently available in the development builds of OpenMQTTGateway.
