### ISSUE TITLE
Add support for stove hood/Safera Sense/RørosHetta

### ISSUE THREAD

**Issue by Takst3in** [theengs/decoder#552]
Hi, attached is the raw logged data from a bluetooth connection to my Safera Sense unit (stove overcooking protection unit) in my RørosHetta hood in the kitchen. Is it possible to try implement support for this device? There are several interesting real-time measurements of air-quality and stuff in this data, that would be great to have in my HomeAssistant.

[Log 2024-07-30 18_38_24.txt](https://github.com/user-attachments/files/16438022/Log.2024-07-30.18_38_24.txt)

**Comment by DigiH** [comment]
Hi @Takst3in 

Theengs Decoder can currently only receive and decode BLE advertising data, but not any GATT service/characteristics, only accessible through connection.

Does the Safera Sense unit broadcast any advertising data which might include decodable information?

You want to set 
```

-padv PUBLISH_ADVDATA, --publish_advdata PUBLISH_ADVDATA
                        Publish advertising and advanced data (1) or not (0)
                        (default: 0)
```

to 1/true to see any, as of yet undecoded, raw advertising data.

**Comment by Takst3in** [comment]
Hi, no the unit does not broadcast any useful data without any connection. I might be mixing 1technophile's other modules, this might be more doable in the "OpenMQTTGateway", or am I wrong?

**Comment by DigiH** [comment]
With OpenMQTTGateway there are the READ and WRITE commands for accessing certain service/characteristics via connection, but there seems to be an issue with these in the latest release and current development version.

**Comment by Takst3in** [comment]
@DigiH Thanks for info, much appreciated 👍

Using OMG v1.6.0 (previous version) on a ESP32, Ive tried to use the command below without success. Any ideas?

  mosquitto_pub -t home/OMG_ESP32_BLE/commands/MQTTtoBT -m '{
  "ble_read_address":"DD:D5:74:67:8E:0D",
  "ble_read_service":"0000f00d-1212-efde-1523-785fef13d123",
  "ble_read_char":"0000beef-1212-efde-1523-785fef13d123",
  "value_type":"STRING",
  "immediate": true,
  "ttl": 2 }'

**Comment by Takst3in** [comment]
Seems like it were a matter of formatting the command, I were able to get the command sent, and recognized.

When the hood were in pairing mode, and the command was sent, i were able to get the expected data one time. After this pairing mode ends, and several attempts of sending the command gets "failed" return/no data. 
Device needs to be set back to pairing mode, to be able to receive the data "one time, again". 

Seems like pairing is not successful, any idea how to?

**Comment by DigiH** [comment]
I honestly don't know what might be the issue with your specific device and it requiring to be in pairing mode ;( 

Might be better taking this to the OpenMQTTGateway discussions, possibly it might need a pairing code to be entered, which is not implemented in OpenMQTTGateway yet.

**Comment by Takst3in** [comment]
Closing this issue, since a duplicate is created here; https://github.com/1technophile/OpenMQTTGateway/issues/1995
