### ISSUE TITLE
Please replace reference to BresserWeatherSensorTTN

### ISSUE THREAD

**Issue by matthias-bs** [theengs/decoder#592]
Hi,

In [README.md](https://github.com/theengs/decoder/blob/development/README.md), you are kindly referring to [BresserWeatherSensorTTN](https://github.com/matthias-bs/BresserWeatherSensorTTN), which is deprecated in favour of [BresserWeatherSensorLW](https://github.com/matthias-bs/BresserWeatherSensorLW). I would like to ask you to update this reference accordingly.
Thanks in advance!

Best regards
Matthias

**Comment by DigiH** [comment]
Hi @matthias-bs 

Done ;)
