### ISSUE TITLE
One of my Xiaomi Mi Flora plant sensors isn't detected

### ISSUE THREAD

**Issue by koenvervloesem** [theengs/decoder#66]
**Describe the bug**

I have three [Xiaomi Mi Flora](https://theengs.github.io/decoder/devices/HHCCJCY01HHCC.html#xiaomi-mi-flora) plant sensors. Two have a green casing and are decoded correctly by Theengs Decoder; one has a white casing and isn't decoded.

**To Reproduce**

1. Data processed: service data 3102980000ad65678d7cc40d on UUID 0xfe95
2. Expected data: temperature, moisture, fertility, luminance
3. Not detected as Mi Flora sensor

**Expected behavior**

I expect Theengs Decoder to decode data from this Mi Flora sensor's service data (for UUID 0xfe95) just like it does for the other ones.

**Screenshots**

This is how OpenMQTTGateway v0.9.10 with Theengs Decoder v0.1.9 sees the advertisements of the device:

```shell
$ mosquitto_sub -t 'home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD' -v|ts
Feb 12 19:58:25 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"rssi":-92,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 19:59:23 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-94,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:01:42 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-94,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:01:49 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-93,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:02:49 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-89,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:03:53 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-90,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:04:58 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-88,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:08:17 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-95,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:11:32 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-95,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:12:47 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-90,"servicedata":"3102980000ad65678d7cc40d"}
Feb 12 20:13:53 home/OpenMQTTGateway_ESP32_OLM_GTWE/BTtoMQTT/C47C8D6765AD {"id":"C4:7C:8D:67:65:AD","mac_type":0,"name":"Flower care","rssi":-93,"servicedata":"3102980000ad65678d7cc40d"}
```

Note that the data are always the same 12 bytes, so I'm not sure whether the device is faulty. The data seem to have a different format (``31029800...``) than the other two Mi Flora devices (``71209800...``).

**Environment (please complete the following information):**

* Theengs Decoder v0.1.9
* OpenMQTTGateway v0.9.10

**Additional context**

The same happens when I'm using Theengs Decoder directly with ``python3 python/ScanAndDecode.py``.

**Comment by 1technophile** [comment]
Interesting, could you share a picture of those. It could help differentiate them. I suppose they have the same model reference?

**Comment by koenvervloesem** [comment]
Here are the three of them:

![image20220214_083110177](https://user-images.githubusercontent.com/214673/153819839-097099a9-3a2f-4f52-99d8-cff0c419f290.jpg)

Apart from their color, they look the same.

Here's a close-up of the printed text on the electrodes of the white Mi Flora sensor:

![image20220214_083125540](https://user-images.githubusercontent.com/214673/153820075-c837b1a2-a894-47de-94b8-fd2ce75febc5.jpg)

The model is printed as HHCCJCY01HHCC, just like on the other ones.

**Comment by 1technophile** [comment]
Thanks for sharing, I think this format could be added in the [decoder condition](https://github.com/theengs/decoder/blob/1f310749ae8206c51fb367cac41c1b7ffb467788/src/devices/HHCCJCY01HHCC_json.h#L7) with a unit test:
```
   "condition":["servicedata", "contain", "209800","|","servicedata", "contain", "029800"],
```

**Comment by koenvervloesem** [comment]
I already tried this, but this isn't enough. The data are 12 bytes instead of 16 to 18 bytes for the other ones, and the current decoder reads data from character 30, which isn't there in these 12 byte data (which go from character 0 to 23). This looks like a different format. But I'm beginning to think it's some kind of error or status message, as the data aren't changing. I was hoping someone had seen the same behavior and could give me some clue.

**Comment by 1technophile** [comment]
Did you checked the version of the mi flora firmware against the others?

**Comment by koenvervloesem** [comment]
Weird, the official Flower Care app for Android (which I wanted to use to read the firmware version) doesn't seem to detect the device either. I know I have been able to read the data in the past with https://github.com/zewelor/bt-mqtt-gateway but now it doesn't anymore.

**Comment by 1technophile** [comment]
Are the service data changing over time or is it always the same?

**Comment by koenvervloesem** [comment]
They have been the same since a few days now... Even after a battery change.

**Comment by 1technophile** [comment]
Do you see values in the mobile app?

**Comment by koenvervloesem** [comment]
No. While I could read sensor values from that specific Mi Flora device in the past with other software, none of the available solutions seem to be able to read these values currently. I'll close this issue, because this looks like a malfunctioning device.
